# Generated by Django 4.0.1 on 2022-01-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='producto',
            new_name='nombre',
        ),
    ]
